<?php

namespace AppBundle\Repository;

/**
 * RefreshTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefreshTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
