# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
# Register listener of language switching.
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    securityUtil:
        class: AppBundle\Service\SecurityUtil
        arguments: ['@security.token_storage', '@doctrine.orm.entity_manager']

    clientService:
        class: AppBundle\Service\ClientService
        arguments: ['@doctrine.orm.entity_manager', '@fos_oauth_server.client_manager.default']

    depositMoneyService:
        class: AppBundle\Service\DepositMoneyService
        arguments: []

    requestPaymentService:
        class: AppBundle\Service\RequestPaymentService
        arguments: []

    developerValidatorV1Service:
        class: AppBundle\Service\DeveloperValidatorV1Service
        arguments: ['@securityUtil', '@doctrine.orm.entity_manager']

    depositMoMoV1Service:
        class: AppBundle\Service\DepositMoMoV1Service
        arguments: ['@depositmoneyservice', '@request_stack', '@logger', '@developerValidatorV1Service', '@doctrine.orm.entity_manager', '@mailer']

    requestPaymentMoMoV1Service:
        class: AppBundle\Service\RequestPaymentMoMoV1Service
        arguments: ['@depositmoneyservice', '@requestpaymentservice', '@request_stack', '@logger', '@developerValidatorV1Service', '@doctrine.orm.entity_manager', '@mailer','@router']