idjangui:
    resource: "@AppBundle/Controller/"
    type:     annotation

request_payment_completed:
    path:     /requestpaymentCompleted
    defaults: { _controller: AppBundle:Default:requestPaymentCompleted }

